### ISSUE TITLE
Receiving error "AssertionError: terrain index matching map index" 

### ISSUE THREAD

**Issue by Br00ty** [beauxq/zilliandomizer#2]
So I just found this and wanted to start messing with it, but upon installing and trying to run, I am getting the following error in cmd prompt:

"found rom at ..\roms\Zillion (UE) [!].sms
Traceback (most recent call last):
  File "E:\ROMS\Sega Mastersystem\zilliandomizer-master\src\generate.py", line 15, in <module>
    main()
  File "E:\ROMS\Sega Mastersystem\zilliandomizer-master\src\generate.py", line 11, in main
    generate(seed)
  File "E:\ROMS\Sega Mastersystem\zilliandomizer-master\src\zilliandomizer\generator.py", line 23, in generate
    p = Patcher()
  File "E:\ROMS\Sega Mastersystem\zilliandomizer-master\src\zilliandomizer\patch.py", line 58, in __init__
    self.tc = TerrainCompressor(self.rom)
  File "E:\ROMS\Sega Mastersystem\zilliandomizer-master\src\zilliandomizer\terrain_compressor.py", line 78, in __init__
    self.load(rom)
  File "E:\ROMS\Sega Mastersystem\zilliandomizer-master\src\zilliandomizer\terrain_compressor.py", line 96, in load
    assert map_index == row * 8 + col, "terrain index matching map index"
AssertionError: terrain index matching map index"

Any ideas on what this could be and how to solve?

edit: looking in the Setup.cfg, it looks like its calling for Python 3.8, now I wonder if theres anyway to get it to work for 3.7. also downloaded/installed newest python version from python.org and it still gives me the same error.

**Comment by beauxq** [comment]
Thanks. I didn't know there were multiple versions of the rom.

I'll put a note about the version in the readme.

**Comment by Br00ty** [comment]
Awesome! was also curious too, but what have you been using to run this game? It seems like Bizhawk wont run it with a handful of bios' I have, and it just gives a "software error" message after the sega logo!

**Comment by beauxq** [comment]
I haven't tried bizhawk, since I don't run Windows. I've used RetroArch and Emulicious for testing.

**Comment by Br00ty** [comment]
Ahhh, okay. So far I've gotten the randomizer to work on the Fusion emulator, but I'll have to check out the other two. Very fun rando!
